### ISSUE TITLE
css 변환 대상이  파싱되는 파일에서 문자열 전체가 해당되는건가요? 

### ISSUE THREAD

**Issue by easylogic** [developer-1px/adorable-css#16]
현재 jsx 기반 내에서 사용을 해보고 있는데요. 

```jsx

class A {
 
   ['refreshAll'] () {
         return <div 
                class="artboard-title is-not-drag-area" 
                data-artboard-title-id={artboardItem.id} 
                style={{
                    "transform-origin": "0% 0%",
                    "transform": `translate3d( calc(${newPointer[0]}px), calc(${newPointer[1]}px), 0px) rotateZ(${angle}deg)`  
                }} >
                    <div style="transform: translateY(-100%);">{artboardItem.title}</div>
            </div>
   } 
}

```

위와 같은 소스가 있다고 치면 

entry 쪽에   대략 아래와 같이 찍힙니다. 

```js
refreshAll
[data-artboard-title-id='${id}']
translate3d(
calc(${newPointer[0]}px),
calc(${newPointer[1]}px),
0px)
rotateZ(${angle}deg)
```

그래서 rotateZ 도 해석이 되는 상태라 최종 css 가 아래 처럼 찍히는데요. 

```css
*{margin:0;padding:0;box-sizing:border-box;font:inherit;color:inherit;flex-shrink:0;}
.rotateZ\(\$\{angle\}deg\){transform:rotateZ(${angle}deg);}
.sepia\(0\.2\){filter:sepia(0.2)}

```

키워드/함수에 대한 파싱 범위를 어디로 보면 좋을까요?
