### ISSUE TITLE
[문의] 특정 selector 에 따라 하위 class 의 기능을 다르게 하고 싶은데요. 이런것도 가능한가요? 

### ISSUE THREAD

**Issue by easylogic** [developer-1px/adorable-css#17]
UI 를 만들다보면 상태에 따라 다른 속성을 보여주고 싶을 때가 있는데요. 

혹시 이런 식으로도 작성이 가능한가요?  

```css
a {
  color: red;

  .selected {
        color: blue;      
  }
}

```

대략 혼자 상상해본 문법은 이렇습니다. 

```js
class="if(parent.selected):c(blue)" 
```
