### ISSUE TITLE
media-query 직접 입력할 수 있도록 할것!. 기능은 구현했는데 문법이 고민됩니다... ex) @sm:w(500)  @max-width(300) ...

### ISSUE THREAD

**Issue by developer-1px** [developer-1px/adorable-css#22]
```css
@media (max-width: 480px) {
  body {
    background-color: red;
  }
}
```

media쿼리 prefix를 어떠한 문법을 통해서 만들면 좋을지 생각해보자..

1) 일단 full 스펙을 지원해서 새로운 CSS 스펙이 나와도 대응을 할 수 있게 한다.

```html
<div class="@media(max-width:480px):bg(red)">hello</div>
<div class="@media(min-width:480px)and(max-width:680px):bg(red)">hello</div>

<div class="@supports not (display: grid) {"></div <!-- 이런것도?? -->

```

2)
media query level 4 문법

@media (600px < width < 1000px)

```html
<div class="@media(600px<width<100px):bg(red)">hello</div>

<div class="@media(600px<width<100px/or/height>100):bg(red)">hello</div>
```

3) mediaQuery는 config에서 할 수 있게

4) 어차피 breakpoint가 대부분일텐데

```html
<div class="@width(768~1024):bg(red)">hello</div>
<div class="@w(768~1024):bg(red)">hello</div>
```

4-1) device-width는?

```html
<div class="@deivce-width(768~1024):bg(red)">hello</div>

<div class="@dw(768~1024):bg(red)">hello</div>
```

**Comment by developer-1px** [comment]
데미안 피셜~~ ~는 필수 문법으로 가져갑시다! 시각으로 min-width를 많이 쓴다 하더라도 직관적인 ux가 좋은 거 같아요

**Comment by developer-1px** [comment]
최종 문법

```html
<div class="@w(360~):c(red)"></div>
<div class="@w(~720):c(red)"></div>
<div class="@w(360~720):c(red)"></div>
```

```css
@media only screen and (min-width:360px){html .\@w\(360\~\)\:c\(red\){color:red;}}
@media only screen and (max-width:719.98px){html .\@w\(\~720\)\:c\(red\){color:red;}}
@media only screen and (min-width:360px and max-width:719.98px){html .\@w\(360\~720\)\:c\(red\){color:red;}}
```
